version: '3.8'
services:
  postgres:
    container_name: sankaku-uploads
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uploads
    volumes:
      - ./database:/var/lib/postgresql/data
