module.exports = {
  apps: [
    {
      name: "danbooru",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 1,
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "zerochan",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 1,
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "rule34",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 1,
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "gelbooru",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 1,
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "yandere",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 1,
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "1G",
      watch: false,
      restart_delay: 1000,
    },
  ],
};
