module.exports = {
  apps: [
    {
      name: "danbooru",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 2,
      merge_logs: false,
      autorestart: true,
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "rule34",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 2,
      merge_logs: false,
      autorestart: true,
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "gelbooru",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 2,
      merge_logs: false,
      autorestart: true,
      watch: false,
      restart_delay: 1000,
    },
    {
      name: "yandere",
      script: "script/uploaders/upload.js",
      exec_mode: "cluster",
      instances: 2,
      merge_logs: false,
      autorestart: true,
      watch: false,
      restart_delay: 1000,
    },
  ],
};
